version: "3.8"

services:
   db:
      image: postgres:14.1-alpine
      container_name: usuarios
      restart: always
      environment: 
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=modulousuarios
      ports:
         - '5432:5432'
      volumes: 
         - pgdata:/var/lib/postgresql/data
      network_mode: host
   app:
      build: .
      container_name: back-usuarios
      ports:
         - 3333:3333
      volumes:
         - .:/usr/app
      network_mode: host
volumes: 
   pgdata:
      driver: local